#############################################################################
# Makefile for building: parent
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Oct 4 13:17:09 2011
# Project:  parent.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile parent.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qtcmislib \
		sub-demo

qtcmislib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtcmislib/ || $(MKDIR) qtcmislib/ 
	cd qtcmislib/ && $(QMAKE) /home/nick/tmp/cmis_qt/qtcmislib/qtcmislib.pro -unix -o $(MAKEFILE)
sub-qtcmislib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtcmislib/ || $(MKDIR) qtcmislib/ 
	cd qtcmislib/ && $(QMAKE) /home/nick/tmp/cmis_qt/qtcmislib/qtcmislib.pro -unix -o $(MAKEFILE)
sub-qtcmislib: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE)
sub-qtcmislib-make_default-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) 
sub-qtcmislib-make_default: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) 
sub-qtcmislib-make_first-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) first
sub-qtcmislib-make_first: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) first
sub-qtcmislib-all-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) all
sub-qtcmislib-all: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) all
sub-qtcmislib-clean-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtcmislib-clean: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtcmislib-distclean-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtcmislib-distclean: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtcmislib-install_subtargets-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) install
sub-qtcmislib-install_subtargets: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) install
sub-qtcmislib-uninstall_subtargets-ordered: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qtcmislib-uninstall_subtargets: qtcmislib//$(MAKEFILE) FORCE
	cd qtcmislib/ && $(MAKE) -f $(MAKEFILE) uninstall
demo//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) /home/nick/tmp/cmis_qt/demo/demo.pro -unix -o $(MAKEFILE)
sub-demo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) /home/nick/tmp/cmis_qt/demo/demo.pro -unix -o $(MAKEFILE)
sub-demo: demo//$(MAKEFILE) sub-qtcmislib FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE)
sub-demo-make_default-ordered: demo//$(MAKEFILE) sub-qtcmislib-make_default-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) 
sub-demo-make_default: demo//$(MAKEFILE) sub-qtcmislib-make_default FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) 
sub-demo-make_first-ordered: demo//$(MAKEFILE) sub-qtcmislib-make_first-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) first
sub-demo-make_first: demo//$(MAKEFILE) sub-qtcmislib-make_first FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) first
sub-demo-all-ordered: demo//$(MAKEFILE) sub-qtcmislib-all-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) all
sub-demo-all: demo//$(MAKEFILE) sub-qtcmislib-all FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) all
sub-demo-clean-ordered: demo//$(MAKEFILE) sub-qtcmislib-clean-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) clean
sub-demo-clean: demo//$(MAKEFILE) sub-qtcmislib-clean FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) clean
sub-demo-distclean-ordered: demo//$(MAKEFILE) sub-qtcmislib-distclean-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demo-distclean: demo//$(MAKEFILE) sub-qtcmislib-distclean FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demo-install_subtargets-ordered: demo//$(MAKEFILE) sub-qtcmislib-install_subtargets-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) install
sub-demo-install_subtargets: demo//$(MAKEFILE) sub-qtcmislib-install_subtargets FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) install
sub-demo-uninstall_subtargets-ordered: demo//$(MAKEFILE) sub-qtcmislib-uninstall_subtargets-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-demo-uninstall_subtargets: demo//$(MAKEFILE) sub-qtcmislib-uninstall_subtargets FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: parent.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile parent.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile parent.pro

qmake_all: sub-qtcmislib-qmake_all sub-demo-qmake_all FORCE

make_default: sub-qtcmislib-make_default-ordered sub-demo-make_default-ordered FORCE
make_first: sub-qtcmislib-make_first-ordered sub-demo-make_first-ordered FORCE
all: sub-qtcmislib-all-ordered sub-demo-all-ordered FORCE
clean: sub-qtcmislib-clean-ordered sub-demo-clean-ordered FORCE
distclean: sub-qtcmislib-distclean-ordered sub-demo-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qtcmislib-install_subtargets-ordered sub-demo-install_subtargets-ordered FORCE
uninstall_subtargets: sub-qtcmislib-uninstall_subtargets-ordered sub-demo-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

