# #####################################################################
# Automatically generated by qmake (2.01a) Fri Sep 30 17:57:56 2011
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += demo.cpp
HEADERS += demo.h
